#!/bin/bash

destination_dir="assets"

latest_version=$(curl "https://registry.npmjs.org/@catala-lang/catala-web-assets/latest" -s | grep -oP '"version":"\K[0-9]+\.[0-9]+(\.[0-9]+)?(-[a-zA-Z]+(\.[0-9]+)?)?')

echo "Latest version: $latest_version"
if [ -d "node_modules/@catala-lang/catala-web-assets-$latest_version" ]; then
    echo "Already up to date"
else
   echo "Adding latest version $latest_version"
   yarn add @catala-lang/catala-web-assets-$latest_version@npm:@catala-lang/catala-web-assets@$latest_version
fi

for folder in node_modules/@catala-lang/catala-web-assets-*; do
    if [ -d "$folder" ]; then
        version_number=$(echo "$folder" | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?(-[a-zA-Z]+(\.[0-9]+)?)?')

        mkdir -p "$destination_dir/$version_number"

        cp $folder/assets/allocations_familiales.html $destination_dir/$version_number/
        cp $folder/assets/allocations_familiales_schema_fr.json $destination_dir/$version_number/
        cp $folder/assets/allocations_familiales_ui_schema_fr.json $destination_dir/$version_number/
        
	cp $folder/assets/aides_logement.html $destination_dir/$version_number/
	cp $folder/assets/aides_logement_schema_fr.json $destination_dir/$version_number/
        cp $folder/assets/aides_logement_ui_fr.schema.jsx $destination_dir/$version_number/
        cp $folder/assets/aides_logement_init.json $destination_dir/$version_number/
        
        echo "Created $destination_dir/$version_number"
    fi
done
