#!/bin/bash

destination_dir="french-law"

for folder in node_modules/@catala-lang/french-law-*; do
    if [ -d "$folder" ]; then
        version_number=$(echo "$folder" | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?(-[a-zA-Z]+(\.[0-9]+)?)?')

        mkdir -p "$destination_dir/$version_number"

        cp $folder/src/french_law.js $destination_dir/$version_number/
        
        echo "Created $destination_dir/$version_number"
    fi
done
